#! /bin/bash
if [ -f .workRemote ]; then
	work_remote=$( cat .workRemote )
elif [ -d .workRemote ] ; then
	work_remote=`realpath .workRemote`
else
	work_remote="/path/to/remote/directory/"
fi

exld=" --exclude '.workRemote' "

work_local=`dirname $(realpath ${BASH_SOURCE[0]})`

confirm1ce=1
updown='unknown'

for v in $@ ; do
	if [ $v == 'up' ] ; then
		updown='up'
		echo "current comand: $updown"
	elif [ $v == 'down' ] ; then
		updown='down'
		echo "current comand: $updown"
	elif [ $v == '-y' ] ; then
		confirm1ce=0
	fi
done

function doconfirm {
	echo $1
	if [ $confirm1ce == 1 ] ; then 
		read -p "OK"
	fi
}
		
cmd="echo nothing specified"

if [ $updown == 'down' ] ; then
	cmd="rsync -avtu $exld $work_remote/ ${work_local%%/}"
elif [  $updown == 'up' ] ; then
    cmd="rsync -avtu $exld $work_local/ ${work_remote%%/}"
fi

doconfirm "$cmd"

# sh -c "$cmd"
